export const ADD_QUESTION = 'ADD_QUESTION';
export const FETCH_ALL_QUESTION = 'FETCH_ALL_QUESTION';
export const FETCH_ALL_QUESTION_SUCCESS = 'FETCH_ALL_QUESTION_SUCCESS';
export const FETCH_ALL_QUESTION_FAILURE = 'FETCH_ALL_QUESTION_FAILURE';

export const SEARCH_QUESTIONS = 'SEARCH_QUESTIONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCHTERM = 'SET_SEARCHTERM';
export const RESET_SEARCH_RESULT = 'RESET_SEARCH_RESULT';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';
export const FETCH_ALL_UNANSWERED_QUESTION = 'FETCH_ALL_UNANSWERED_QUESTION';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const LIKE_QUESTION_SUCCESS = 'LIKE_QUESTION_SUCCESS';
export const SET_ANSWERS_BY_QUESTION = 'SET_ANSWERS_BY_QUESTION';
export const NEW_QUESTION_ANSWERED = 'NEW_QUESTION_ANSWERED';
export const DELETE_ANSWERED_QUESTION_SUCCESS =
  'DELETE_ANSWERED_QUESTION_SUCCESS';
export const DELETE_UNANSWERED_QUESTION_SUCCESS =
  'DELETE_UNANSWERED_QUESTION_SUCCESS';

export const SET_QUESTION = 'SET_QUESTION';
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
export const UPDATE_FOCUSED_QUESTION_ANSWER = 'UPDATE_FOCUSED_QUESTION_ANSWER';
