export const ADD_QUESTION = 'ADD_QUESTION'
export const FETCH_ALL_QUESTION = 'FETCH_ALL_QUESTION'
export const FETCH_ALL_QUESTION_SUCCESS = 'FETCH_ALL_QUESTION_SUCCESS'
export const FETCH_ALL_QUESTION_FAILURE = 'FETCH_ALL_QUESTION_FAILURE'
